import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import { Layout } from '@Components';

const Home: NextPage = () => {
    return (
        <Layout>
            <div className={styles.container}>
                <Head>
                    <title>NextAuth.js Example</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <main className={styles.main}>
                    <h1 className={styles.title}>
                        NextAuth.js Example Project
                    </h1>
                    <div className={styles.accountInfo}>
                        <Link className={styles.link} href="/protected">
                            Protected
                        </Link>
                    </div>
                </main>
            </div>
        </Layout>
    );
};

export default Home;
